name: LePark
favicon: null
layout_spectrum: 1
typography_spectrum: 0.46721
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#343235'
    - '#f3f1f4'
    - '#b3b1b4'
    - '#979598'
    - '#4e4c4f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
