name: LePark
favicon: null
layout_spectrum: 1
typography_spectrum: 0.46721
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ece7e4'
    - '#d4cac8'
    - '#b8b9bd'
    - '#a29897'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
